# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Develop Merge CI

on:
  push:
    branches:
      - develop

  # Add necessary env
  # env:
  # The sanity env is used by storybook.
  # NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID}}
  # NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET}}
  # NEXT_PUBLIC_SANITY_API_VERSION: ${{ secrets.NEXT_PUBLIC_SANITY_API_VERSION}}
  # CHROMATIC_DISABLE_SNAPSHOT: false
  # SANITY_URL: https://lemonhive.sanity.studio/development/desk

# Cancel in-progress actions when a new action is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run tsc
      - run: npm run lint
      - run: npm run prettier
      - run: npm run test
      # Comment chromatic and summary
      # - name: Publish to Chromatic
      #   id: chromatic
      #   uses: chromaui/action@v1
      #   # Chromatic GitHub Action options
      #   with:
      #     # 👇 Chromatic projectToken, refer to the manage page to obtain it.
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      #     onlyChanged: true
      # - name: Publish Summary
      #   run: echo -e "| Results |  |\n| --- | --- |\n| Chromatic | ${{steps.chromatic.outputs.buildUrl}} |\n| Storybook Preview | ${{steps.chromatic.outputs.storybookUrl}} |\n| Sanity | $SANITY_URL |" >> $GITHUB_STEP_SUMMARY
